name: aws-terraform-deploy-staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Package source code to deployment
        run: zip -r application.zip src/ 

      - name: Upload ZIP file
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: application.zip

  setup-infra:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform -chdir=staging/ init

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=staging/ fmt -recursive

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=staging/ validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=staging/ plan

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=staging/ apply -auto-approve

  deploy:
    runs-on: ubuntu-latest
